name: /work/data1/liutianyuan/env/tss
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - comm=0.2.3
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.3
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - libedit=3.1.20250104
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libsodium=1.0.20
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.6.0
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.3
  - platformdirs=4.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.3
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - biopython==1.86
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.19.1
      - fonttools==4.61.0
      - frozenlist==1.8.0
      - fsspec==2025.9.0
      - idna==3.4
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - llvmlite==0.46.0
      - logomaker==0.8.7
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - multidict==6.7.0
      - networkx==3.3
      - numba==0.63.1
      - numpy==1.26.4
      - pandas==2.3.3
      - pillow==11.3.0
      - propcache==0.4.1
      - pyg-lib==0.4.0+pt21cu118
      - pynndescent==0.5.13
      - pyparsing==3.2.5
      - pytz==2025.2
      - requests==2.28.1
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - torch==2.1.2+cu118
      - torch-cluster==1.6.3+pt21cu118
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2+pt21cu118
      - torch-sparse==0.6.18+pt21cu118
      - torch-spline-conv==1.2.2+pt21cu118
      - torchaudio==2.1.2+cu118
      - torchvision==0.16.2+cu118
      - tqdm==4.67.1
      - triton==2.1.0
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - urllib3==1.26.13
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /work/data1/liutianyuan/env/tss
